### ISSUE TITLE
reflow() Not Working After Dynamically Adding Items to Grid

### ISSUE THREAD

**Issue by liucf** [chiribuc/vue-stack-grid#1]
### Issue: `reflow()` Not Working After Dynamically Adding Items to Grid

**Description:**  
I am dynamically appending items to a grid using Vue. After pushing the new items to the list, I attempted to trigger a reflow using `stackGridRef.value.reflow();`, but it does not work.

However, if I add a button like this:  

```html
<button @click="reflowGrid">Reflow Grid</button>
```

With the following method:  

```javascript
function reflowGrid() {
  if (stackGridRef.value) {
    stackGridRef.value.reflow();
  }
}
```

Clicking the button does successfully trigger the reflow.

---

### Question:  
Why doesn't `stackGridRef.value.reflow();` work immediately after appending new items? Are there any suggestions or best practices to ensure the grid reflows dynamically after adding items?

Thanks for your help!  

--- 

This format is concise, clear, and ready for submission on GitHub!

**Comment by chiribuc** [comment]
Hi there, thanks for using the package.

You are right, I will update the lib to update the grid after the items change but until then you can call `reflow()` when your items array changes.

**Comment by liucf** [comment]
Hi, Thanks for your reply.

I tried call `reflow()` after items array changes, but it did NOT work. look like the images are stack on each other.
Here is my code.

```
	axios
	.get(`${props.items.meta.path}?cursor=${props.items.meta.next_cursor}`)
	.then((response) => {
		props.items.data.push(...response.data.data);
               stackGridRef.value.reflow();
         });
		
```

**Comment by liucf** [comment]
hmm, got this error for v1.0.3 `[vite] Internal server error: Failed to resolve entry for package "@crob/vue-stack-grid". The package may have incorrect main/module/exports specified in its package.json`

**Comment by chiribuc** [comment]
@liucf uninstall the package `npm uninstall @crob/vue-stack-grid` and install it again `npm i --save @crob/vue-stack-grid`

**Comment by mdxiaohu** [comment]
Title
[TS] Template slot `#item` causes type error: Property 'item' does not exist on type '{}'

Description

When using @crob/vue-stack-grid in a Vue 3 + TypeScript project, accessing the item slot in a template triggers the following TypeScript error:

Property '{}' has no property 'item'. ts-plugin(2339)


Example:

<stack-grid :items="configCardList" :column-min-width="360" :gutter-width="15" :gutter-height="15">
  <template #item="{ item, key }">
    <symbol-card :card-data="item" :key="key" />
  </template>
</stack-grid>


The component works correctly at runtime, but TypeScript reports a type error.

Steps to Reproduce

Install @crob/vue-stack-grid in a Vue 3 + TypeScript project.

Use the #item="{ item }" slot in a template.

Observe TypeScript error: Property '{}' has no property 'item'.

Expected Behavior

TypeScript should correctly infer the type of the item slot. Ideally, the library should provide type declarations for the slots so that this usage works without errors.

I have submitted a pull request. If possible, please approve it. I am unable to submit issues and can only contact you here.

@chiribuc
